DROP TABLE CurriculumVitae;
/
DROP TABLE Experience;
/
DROP TABLE Studies;
/
DROP TABLE LanguageSkills;
/
DROP TABLE Hobbies;
/
DROP TABLE SoftSkills;
/
DROP TABLE Technical_skills;
/
DROP TABLE Social_skills;
/

CREATE TABLE CurriculumVitae(
  ID NUMBER primary key,
  CLUSTER_ID VARCHAR2(3),
  NAME VARCHAR2(256),
  DATE_OF_BIRTH DATE,
  ADDRESS VARCHAR2(256),
  PHONE_NUMBER NUMBER(10),
  EMAIL VARCHAR2(256),
  EXPERIENCE_YEARS NUMBER,
  IDEAL_JOB VARCHAR2(256)
);
/

CREATE TABLE Experience(
  PERSON_ID NUMBER not null,
  JOB_TITLE VARCHAR2(256),
  EXPERIENCE_YEARS NUMBER
);
/

CREATE TABLE Studies(
  PERSON_ID NUMBER not null,
--  0 - LICEU; 
--  2 - LICENTA
--  4 - MASTER
--  6 - DOCTORAT
  CERTIFICATE NUMBER,
  STUDY_YEARS NUMBER
);
/

CREATE TABLE LanguageSkills(
  PERSON_ID NUMBER not null,
  LANGUAGE CLOB
);
/

CREATE TABLE Hobbies(
  PERSON_ID NUMBER not null,
  HOBBY CLOB
);
/

CREATE TABLE SoftSkills(
  PERSON_ID NUMBER not null,
  TECHNICAL_SKILL_ID NUMBER,
  SOCIAL_SKILL_ID NUMBER
);
/

CREATE TABLE TECHNICAL_SKILLS(
   TECHNICAL_SKILL_ID NUMBER not null,
   SKILL CLOB
);
/

CREATE TABLE SOCIAL_SKILLS(
  SOCIAL_SKILL_ID NUMBER not null,
  SKILL CLOB
);
/