DROP TABLE CurriculumVitae;
/
DROP TABLE Experience;
/
DROP TABLE Studies;
/
DROP TABLE LanguageSkills;
/
DROP TABLE Hobbies;
/
DROP TABLE SoftSkills;
/
DROP TABLE Technical_skills;
/
DROP TABLE Social_skills;
/

CREATE TABLE CurriculumVitae(
  ID NUMBER primary key,
  NAME VARCHAR2(256),
  DATE_OF_BIRTH DATE,
  ADDRESS VARCHAR2(256),
  PHONE_NUMBER NUMBER(10),
  EMAIL VARCHAR2(256),
  EXPERIENCE_YEARS NUMBER,
  IDEAL_JOB VARCHAR2(256),
  EXPERIENCE_ID NUMBER,
  STUDIES_ID NUMBER,
  LANGUAGE_ID NUMBER,
  HOBBY_ID NUMBER,
  SOFTSKILL_ID NUMBER
);
/

CREATE TABLE Experience(
  EXPERIENCE_ID NUMBER primary key,
  JOB_TITLE VARCHAR2(256),
  YEARS NUMBER
);
/

CREATE TABLE Studies(
  STUDIES_ID NUMBER primary key,
  INSTITUTE_CERTIFICATE CLOB,
--  CERTIFICATE VARCHAR2(256),
  STUDY_YEAR NUMBER
);
/

CREATE TABLE LanguageSkills(
  LANGUAGE_ID NUMBER primary key,
  LANGUAGE CLOB
);
/

CREATE TABLE Hobbies(
  HOBBY_ID NUMBER primary key,
  HOBBY CLOB
);
/

CREATE TABLE SoftSkills(
  SOFTSKILL_ID NUMBER primary key,
  TECHNICAL_SKILL_ID NUMBER,
  SOCIAL_SKILL_ID NUMBER
);
/

CREATE TABLE TECHNICAL_SKILLS(
   TECHNICAL_SKILL_ID NUMBER primary key,
   SKILL CLOB
);
/

CREATE TABLE SOCIAL_SKILLS(
  SOCIAL_SKILL_ID NUMBER primary key,
  SKILL CLOB
);
/
